spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/market?&character_set_server=utf8mb4&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    context-path: /joinus
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  op-patterns: com.example.fleamarket.service.*
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t6WAjybmXMxC9L5a8ov
      secret-key: AKYs2rqmQSGuCe4pHOMXtBDHJ9cClM
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucketName: flea--market
        filehost: fleaMarket




mybatis:
  mapper-locations:classpath:mapper/*.xml
  type-aliases-package:com.example.ibookreader.entity
  configuration:log-impl:org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  D:/text/
server:
  port: 8989







